### ISSUE TITLE
How to use GA 4 in chrome extension

### ISSUE THREAD

**Issue by mitic0320** [googleanalytics/ga4-tutorials#12]
I am using Universal Analytics with `analytics.js` and I want to migrate to GA4.
I add the tag snippet in my web and it works fine.
But when i add the tag snippet to my chrome extension `popup.html`, it doesn't work. In chrome `network inspector` I can not find the `collect` request.
How can i use GA4 in chrome extension?

**Comment by matt-landers** [comment]
This is unrelated to this project.
