### ISSUE TITLE
Problem with connection to localhost:80 

### ISSUE THREAD

**Issue by yippikaye314** [googleanalytics/ga4-tutorials#14]
I got a problem with the connection to localhost80. After running `deno task start` pops up an error like in the screenshot. I have tried all the solutions suggested in this section also in GA4 and Deno discord servers but the problem still remains. Looks like a problem is in this file (https://github.com/googleanalytics/ga4-tutorials/blob/main/src/index.ts)
@matt-landers Can you please look into this?
![deno2](https://github.com/googleanalytics/ga4-tutorials/assets/128834180/e511ac71-c1f3-402a-80b4-616b5318ccb2)

**Comment by fitzhaile** [comment]
I've had the same problem. Any update?

**Comment by JuhiThakkar** [comment]
I too have same problem and nothing helps, tired passing hardcoded file name but it's not helping.

**Comment by matt-landers** [comment]
I refactored and I don't believe this is an issue anymore. Let me know if it persists.
