### ISSUE TITLE
Deno server not working on Windows 11

### ISSUE THREAD

**Issue by Kallenju** [googleanalytics/ga4-tutorials#8]
I cannot run it on win 11. Deno throw an error:

Task start deno run -A --watch=src/public/ src/index.ts
Watcher Process started.
File server running on http://localhost:80/
index.eta
Error: The filename, directory name, or volume label syntax is incorrect. (os error 123): lstat 'C:\C:\Users\kosty\ga4-tutorials\src\public\index.eta'
    at Object.lstatSync (ext:deno_fs/30_fs.js:339:7)
    at Module.existsSync (https://deno.land/std@0.66.0/fs/exists.ts:23:10)
    at https://deno.land/x/eta@v1.11.0/file-utils.ts:113:19
    at Array.some (<anonymous>)
    at searchViews (https://deno.land/x/eta@v1.11.0/file-utils.ts:108:13)
    at getPath (https://deno.land/x/eta@v1.11.0/file-utils.ts:172:21)
    at renderFile (https://deno.land/x/eta@v1.11.0/file-handlers.ts:259:27)
    at handleHttp (file:///C:/Users/kosty/ga4-tutorials/src/index.ts:37:39)
    at eventLoopTick (ext:core/01_core.js:181:11) {
  code: "ENOENT"
}

**Comment by Kallenju** [comment]
Problem in index.ts file:

`const __dirname = new URL(".", import.meta.url).pathname` results in `/C:/Users/kosty/ga4-tutorials/src/`. Pay attention to `/` at the beginning of the string.

With such `__dirname` on Windows Deno doubles the volume: `'C:\C:\`.

I changed `const __dirname = new URL(".", import.meta.url).pathname` to `const __dirname = new URL(".", import.meta.url).pathname.replace('/', '');` and the website loaded.

**Comment by Titos23** [comment]
I will try it

**Comment by yippikaye314** [comment]
So Deno server not working on both Windows versions?

**Comment by yippikaye314** [comment]
The reason I'm asking is that I have the same problem and so far didn't find any solution, although I asked for help with this issue in Deno and GA4 discord servers

**Comment by Kallenju** [comment]
@yippikaye314 hi, here is a solution https://github.com/googleanalytics/ga4-tutorials/issues/8#issuecomment-1545240337

**Comment by yippikaye314** [comment]
@Kallenju hi, thank you for your answer, but it didn't help
![deno_git](https://github.com/googleanalytics/ga4-tutorials/assets/128834180/756eec2e-399c-4b3b-9d9b-279d55b9e751)

**Comment by Kallenju** [comment]
@yippikaye314 as you can see after `: lstat 'C:\C:\`, there is double 'C:\'.

If you fix this via changing `__dirname` or another base, all will work.

**Comment by yippikaye314** [comment]
@Kallenju I'm new to coding and have very basic skills. Looks like I have to learn js and ts first to be able to fix this ts file to even start with GA4.
