### ISSUE TITLE
Troubleshooting Character Encoding Issues in Google Analytics Reports on Android Devices

### ISSUE THREAD

**Issue by mukiwu** [googleanalytics/ga4-tutorials#9]
I noticed that when I view my website using an Android phone, although the web page displays correctly in the browser with the proper encoding, the titles appear as garbled characters when I access the GA (Google Analytics) reports. This issue occurs on most Android phones, but not all, and the specific versions vary. What could be causing this, and how can I address it?

![1](https://github.com/googleanalytics/ga4-tutorials/assets/3794103/83366af4-f02f-4e42-9971-040b1e881a4a)

![2](https://github.com/googleanalytics/ga4-tutorials/assets/3794103/c7629814-28f0-41cd-a7ac-5f5cd03419fe)

**Comment by matt-landers** [comment]
This is not related to this project. Please reach out to support.
